name: Automated App Preview Build

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Create envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
          envkey_FUNCTION_TOKEN: ${{ secrets.FUNCTION_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build preview app
        run: eas build -p android --profile preview --no-wait